export const allToilets = [
  {
    id: 11739,
    toilet_id: "801109PTB0007",
    external_toilet_id: "801109 P 0011",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8044199",
    longitude: "82.2150297",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:44",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 11745,
    toilet_id: "801109PTB0008",
    external_toilet_id: "801109 P 0012",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8066192",
    longitude: "82.2088158",
    deletedAt: "null",
    status: 1,
    state_qc_status: 0,
    google_status: 0,
    updatedAt: "Dec 22, 2023 16:55:55",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 11749,
    toilet_id: "801109PTB0009",
    external_toilet_id: "801109 P 0013",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8074507",
    longitude: "82.2086763",
    deletedAt: "null",
    status: 1,
    state_qc_status: 0,
    google_status: 0,
    updatedAt: "Dec 23, 2023 11:41:56",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 1,
  },
  {
    id: 11774,
    toilet_id: "801109CTB0004",
    external_toilet_id: "801109 C 0014",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8028373",
    longitude: "82.1927547",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Sep 20, 2018 8:09:46",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 11784,
    toilet_id: "801109CTB0005",
    external_toilet_id: "801109 C 0015",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8084806",
    longitude: "82.1999699",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:25",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 12,
  },
  {
    id: 11793,
    toilet_id: "801109PTB0010",
    external_toilet_id: "801109 P 0016",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8107708",
    longitude: "82.2052076",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:07",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 18,
  },
  {
    id: 11804,
    toilet_id: "801109PTB0011",
    external_toilet_id: "801109 P 0017",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8107659",
    longitude: "82.2061926",
    deletedAt: "null",
    status: 1,
    state_qc_status: 0,
    google_status: 0,
    updatedAt: "Dec 23, 2023 8:50:52",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 11812,
    toilet_id: "801109PTB0012",
    external_toilet_id: "801109 P 0018",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8098319",
    longitude: "82.2075793",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:52",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 12,
  },
  {
    id: 11822,
    toilet_id: "801109PTB0013",
    external_toilet_id: "801109 P 0019",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8099719",
    longitude: "82.2077",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:36",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 11827,
    toilet_id: "801109PTB0014",
    external_toilet_id: "801109 P 0020",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8167465",
    longitude: "82.2129914",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:35",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 6,
  },
  {
    id: 11829,
    toilet_id: "801109PTB0015",
    external_toilet_id: "801109 P 0021",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8071972",
    longitude: "82.2123119",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:23",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 18,
  },
  {
    id: 11834,
    toilet_id: "801109PTB0016",
    external_toilet_id: "801109 P 0022",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8071972",
    longitude: "82.2123119",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:27",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 5,
  },
  {
    id: 11839,
    toilet_id: "801109PTB0017",
    external_toilet_id: "801109 P 0023",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8071972",
    longitude: "82.2123119",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:39",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 18,
  },
  {
    id: 11844,
    toilet_id: "801109PTB0018",
    external_toilet_id: "801109 P 0024",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8070083",
    longitude: "82.21062",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:31",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 11857,
    toilet_id: "801109CTB0006",
    external_toilet_id: "801109 C 0025",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7943025",
    longitude: "82.212131",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:20",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 11862,
    toilet_id: "801109CTB0007",
    external_toilet_id: "801109 C 0026",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8021292",
    longitude: "82.205336",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:40",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12002,
    toilet_id: "801109CTB0008",
    external_toilet_id: "801109 C 0027",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7990839",
    longitude: "82.2044978",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:19",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12009,
    toilet_id: "801109PTB0019",
    external_toilet_id: "801109 P 0028",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7882185",
    longitude: "82.2005765",
    deletedAt: "null",
    status: 1,
    state_qc_status: 0,
    google_status: 0,
    updatedAt: "Dec 22, 2023 16:26:05",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 8,
  },
  {
    id: 12015,
    toilet_id: "801109PTB0020",
    external_toilet_id: "801109 P 0029",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7950381",
    longitude: "82.1982502",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:16",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 20,
  },
  {
    id: 12021,
    toilet_id: "801109CTB0009",
    external_toilet_id: "801109 C 0030",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.797292",
    longitude: "82.2022272",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:32",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12030,
    toilet_id: "801109CTB0010",
    external_toilet_id: "801109 C 0031",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8146096",
    longitude: "82.2099554",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Sep 12, 2018 12:09:04",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 30,
  },
  {
    id: 12039,
    toilet_id: "801109CTB0011",
    external_toilet_id: "801109 C 0032",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.8053665",
    longitude: "82.2046697",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Nov 20, 2018 1:11:23",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12055,
    toilet_id: "801109PTB0021",
    external_toilet_id: "801109 P 0033",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.791944345796335",
    longitude: "82.19950803337689",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Oct 4, 2018 5:10:32",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12058,
    toilet_id: "801109PTB0022",
    external_toilet_id: "801109 P 0034",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7882422",
    longitude: "82.1930529",
    deletedAt: "null",
    status: 1,
    state_qc_status: 0,
    google_status: 0,
    updatedAt: "Dec 22, 2023 13:34:21",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 4,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 0,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
  {
    id: 12062,
    toilet_id: "801109CTB0012",
    external_toilet_id: "801109 C 0035",
    State: "UTTAR PRADESH",
    District: "AYODHYA",
    ulb_id: 801109,
    ULB: "AYODHYA (M.CORP.)",
    pincode: 224123,
    category_id: 1,
    owner_authority: "ULB",
    maintainance_authority: "ULB",
    fees_applicable: 1,
    cost: 5,
    latitude: "26.7889533",
    longitude: "82.1932847",
    deletedAt: "null",
    status: 1,
    state_qc_status: 1,
    google_status: 0,
    updatedAt: "Sep 12, 2018 13:09:53",
    funding_source: 0,
    is_septic_tank: 0,
    saptic_tank_with_soak_pit: 0,
    seat_type: "toilet",
    gender: 0,
    is_aspirational: 0,
    is_child_friendly: 0,
    is_tap_available: 0,
    is_regularly_cleaned: 0,
    is_having_bio_digester: 0,
    is_functional: 1,
    is_differently_abled_friendly: 1,
    is_clean_and_usable: 0,
    seat_id: 10,
  },
];
