export const RainfallData = [
  {
    2017: {
      dayWise: [
        {
          Day: 1,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 42.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 2,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 18,
          Aug: 17.8,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 3,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 2.8,
          Sep: 3,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 4,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 55.2,
          Aug: 0,
          Sep: 5,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 5,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 19.6,
          Aug: 0,
          Sep: 41.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 6,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 7.3,
          Jul: 27.8,
          Aug: 3,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 7,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 5,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 8,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 46.6,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 9,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 8.6,
          Jun: 0,
          Jul: 3.6,
          Aug: 20,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 10,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 2,
          Jun: 0,
          Jul: 5,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 11,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 33.2,
          Jul: 34.6,
          Aug: 9.6,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 12,
          Jan: 0,
          Feb: 0,
          Mar: 0.7,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 9.4,
          Aug: 3.4,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 13,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 14,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 1,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 15,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 10,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 16,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 17,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 14.2,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 18,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 19,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 20,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 26,
          Aug: 5.2,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 21,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 7.2,
          Jul: 0,
          Aug: 0,
          Sep: 14,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 22,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 125.8,
          Aug: 0,
          Sep: 38,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 23,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 9.2,
          Aug: 0.6,
          Sep: 36.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 24,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 32.8,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 25,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 5.2,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 26,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 36,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 27,
          Jan: 6.8,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 1,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 28,
          Jan: 10,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 53,
          Sep: 20.6,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 29,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 30,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 5.4,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 31,
          Jan: 0,
          Mar: 0,
          May: 0,
          Jul: 0,
          Aug: 0,
          Oct: 0,
          Dec: 0,
        },
      ],
      monthWise: [
        {
          Jan: 16.8,
          Feb: 0,
          Mar: 0.7,
          Apr: 0,
          May: 10.6,
          Jun: 71.9,
          Jul: 376.4,
          Aug: 206.2,
          Sep: 200.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
      ],
    },

    2018: {
      dayWise: [
        {
          Day: 1,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 25,
          Sept: 33.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 2,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 3,
          Aug: 43.4,
          Sept: 3,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 3,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 2.5,
          Aug: 23,
          Sept: 2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 4,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 38.8,
          Sept: 42.6,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 5,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 1.4,
          Sept: 3.8,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 6,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 7,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 1,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 8,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 8.6,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 9,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 10,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 11,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 12,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 50,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 13,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 16.8,
          Aug: 2,
          Sept: 27.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 14,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 11,
          June: 0,
          July: 23,
          Aug: 51.4,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 15,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 16,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 17,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 18,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 2,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 19,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 7,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 20,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 5,
          Aug: 3,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 21,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 74.2,
          Aug: 0,
          Sept: 1.6,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 22,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 23,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 62,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 24,
          Jan: 1,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 13.3,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 25,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 0,
          Aug: 22.8,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 26,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 1.2,
          July: 17.4,
          Aug: 35.2,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 27,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 38.2,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 28,
          Jan: 0,
          Feb: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 10.2,
          July: 0,
          Aug: 0,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 29,
          Jan: 0,
          March: 0,
          April: 0,
          May: 0,
          June: 0,
          July: 74,
          Aug: 1,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 30,
          Jan: 0,
          March: 0,
          April: 8.8,
          May: 0,
          June: 1,
          July: 9.6,
          Aug: 26,
          Sept: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 31,
          Jan: 0,
          March: 0,
          May: 0,
          July: 6.6,
          Aug: 2.8,
          Oct: 0,
          Dec: 0,
        },
      ],
      monthWise: [
        {
          Jan: 1,
          Feb: 0,
          March: 0,
          April: 8.8,
          May: 11,
          June: 12.4,
          July: 340.6,
          Aug: 349.4,
          Sept: 113.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
      ],
    },

    2019: {
      dayWise: [
        {
          Day: 1,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 2,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 2,
          Sep: 0,
          Oct: 7,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 3,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 14.6,
          Sep: 0,
          Oct: 3,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 4,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 5,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 6,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 5.8,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 7,
          Jan: 0,
          Feb: 3,
          Mar: 0,
          Apr: 2,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 18,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 8,
          Jan: 0,
          Feb: 6,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 20,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 9,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 13,
          Aug: 0,
          Sep: 10,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 10,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 120.7,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 11,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 63.6,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 12,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 45.6,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 13,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 8,
          Aug: 2,
          Sep: 44.6,
          Oct: 0,
          Nov: 0,
          Dec: 15,
        },
        {
          Day: 14,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 7,
        },
        {
          Day: 15,
          Jan: 0,
          Feb: 2,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 2,
          Sep: 59.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 16,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 3,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 17,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 3,
          Aug: 0,
          Sep: 21,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 18,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 2.4,
          Aug: 0,
          Sep: 13,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 19,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 20,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 11,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 21,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 8,
          Aug: 30,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 22,
          Jan: 0,
          Feb: 2.5,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 2,
          Aug: 6.2,
          Sep: 65,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 23,
          Jan: 3,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 9,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 24,
          Jan: 2,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 4,
          Jul: 35,
          Aug: 4,
          Sep: 13,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 25,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 51.2,
          Aug: 39.2,
          Sep: 11,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 26,
          Jan: 36,
          Feb: 0,
          Mar: 5,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 5,
          Aug: 5.2,
          Sep: 5,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 27,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 85,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 28,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 10.2,
          Aug: 0,
          Sep: 30.6,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 29,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 30.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 30,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 31,
          Jan: 0,
          Mar: 0,
          May: 0,
          Jul: 0,
          Aug: 0,
          Oct: 0,
          Dec: 0,
        },
      ],
      monthWise: [
        {
          Jan: 41,
          Feb: 13.5,
          Mar: 5,
          Apr: 2,
          May: 0,
          Jun: 24,
          Jul: 396.5,
          Aug: 123.2,
          Sep: 396,
          Oct: 10,
          Nov: 0,
          Dec: 22,
        },
      ],
    },

    2020: {
      dayWise: [
        {
          Day: 1,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 11.6,
          Jun: 0,
          Jul: 1.4,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 2,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 1.4,
          Jul: 0,
          Aug: 10.8,
          Sep: 1,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 3,
          Jan: 4,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 22.4,
          Sep: 16.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 4,
          Jan: 3.8,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 4,
          Aug: 13,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 5,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 12.2,
          Jun: 2.8,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 3,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 6,
          Jan: 0,
          Feb: 0,
          Mar: 35,
          Apr: 0,
          May: 4,
          Jun: 6.4,
          Jul: 25,
          Aug: 1,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 7,
          Jan: 0,
          Feb: 0,
          Mar: 33,
          Apr: 0,
          May: 6.2,
          Jun: 0,
          Jul: 55,
          Aug: 10.4,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 8,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 21,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 9,
          Jan: 6.6,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 1.6,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 10,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 11,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 3.8,
          Jun: 0,
          Jul: 57.2,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 12,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 60,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 13,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 92.2,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 14,
          Jan: 0,
          Feb: 0,
          Mar: 9,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 11,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 15,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 3.4,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 16,
          Jan: 2,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 19.6,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 6.2,
          Dec: 0,
        },
        {
          Day: 17,
          Jan: 19,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 28.2,
          Jul: 1.6,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 18,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 4.2,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 19,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 1,
          Jul: 0,
          Aug: 8.2,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 20,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 1,
          Jul: 9.4,
          Aug: 8,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 21,
          Jan: 0,
          Feb: 1,
          Mar: 0,
          Apr: 1,
          May: 0,
          Jun: 74.4,
          Jul: 8,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 22,
          Jan: 0,
          Feb: 20,
          Mar: 2,
          Apr: 0,
          May: 0,
          Jun: 8.6,
          Jul: 1.2,
          Aug: 11.4,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 23,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 1,
          Jul: 1.6,
          Aug: 15,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 24,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 6,
          Jul: 0,
          Aug: 0,
          Sep: 68.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 25,
          Jan: 0,
          Feb: 32,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 8.2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 26,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 10.2,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 27,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 11,
          May: 0,
          Jun: 0,
          Jul: 31,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 28,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 37.8,
          Jul: 4,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 29,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 28.2,
          Jul: 29.8,
          Aug: 5,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 30,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          Day: 31,
          Jan: 0,
          Mar: 0,
          May: 10.8,
          Jul: 4,
          Aug: 0,
          Oct: 0,
          Dec: 0,
        },
      ],
      monthWise: [
        {
          Jan: 35.4,
          Feb: 53,
          Mar: 79,
          Apr: 12,
          May: 48.6,
          Jun: 230.8,
          Jul: 254.2,
          Aug: 273.4,
          Sep: 93.8,
          Oct: 3,
          Nov: 6.2,
          Dec: 0,
        },
      ],
    },

    2021: {
      dayWise: [
        {
          "D/M": 1,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 2,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 33,
          Jul: 0,
          Aug: 2,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 3,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 6.2,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 4,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 1,
          Aug: 0,
          Sep: 0,
          Oct: 3,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 5,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 37.4,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 6,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 8.8,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 7,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 40.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 8,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 2,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 9,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 22,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 10,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 2.8,
          Jul: 0,
          Aug: 30,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 11,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 12,
          Jul: 0,
          Aug: 10,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 12,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 63.6,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 13,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 30.2,
          Jun: 6,
          Jul: 0,
          Aug: 4,
          Sep: 10,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 14,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 34.8,
          Jul: 0,
          Aug: 14.8,
          Sep: 5.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 15,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 49,
          Jul: 0,
          Aug: 0,
          Sep: 106,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 16,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 84.6,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 17,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 41.4,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 18,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 29.8,
          Jul: 27,
          Aug: 0,
          Sep: 0,
          Oct: 10,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 19,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 4.4,
          Jun: 29,
          Jul: 2,
          Aug: 0,
          Sep: 8.6,
          Oct: 7.6,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 20,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 30.2,
          Jun: 2,
          Jul: 3,
          Aug: 1,
          Sep: 54.4,
          Oct: 6.4,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 21,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 16.2,
          Jun: 1.8,
          Jul: 6,
          Aug: 6.6,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 22,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 9.2,
          Aug: 1,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 23,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 2.4,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 24,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 15,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 25,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 4.4,
          Jul: 7.2,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 26,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 10,
          Jul: 18.6,
          Aug: 2,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 27,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 0,
          Jun: 0,
          Jul: 0,
          Aug: 1,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 28,
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 26,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 0,
        },
        {
          "D/M": 29,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 32.2,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 10,
        },
        {
          "D/M": 30,
          Jan: 0,
          Mar: 0,
          Apr: 0,
          May: 1.6,
          Jun: 0,
          Jul: 0,
          Aug: 0,
          Sep: 0,
          Oct: 0,
          Nov: 0,
          Dec: 5,
        },
        {
          "D/M": 31,
          Jan: 0,
          Mar: 0,
          May: 0,
          Jul: 1,
          Aug: 0,
          Oct: 0,
          Dec: 0,
        },
      ],

      monthWise: [
        {
          Jan: 0,
          Feb: 0,
          Mar: 0,
          Apr: 0,
          May: 140.79999999999998,
          Jun: 214.60000000000002,
          Jul: 114.80000000000001,
          Aug: 173,
          Sep: 352.8,
          Oct: 42,
          Nov: 0,
          Dec: 15,
        },
      ],
    },
  },
];

// export const Rainfall2018 = [
//   {
//     Day: 1,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 25,
//     Sept: 33.2,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 2,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 3,
//     Aug: 43.4,
//     Sept: 3,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 3,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 2.5,
//     Aug: 23,
//     Sept: 2,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 4,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 38.8,
//     Sept: 42.6,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 5,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 1.4,
//     Sept: 3.8,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 6,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 7,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 1,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 8,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 8.6,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 9,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 10,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 11,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 12,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 50,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 13,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 16.8,
//     Aug: 2,
//     Sept: 27.2,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 14,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 11,
//     June: 0,
//     July: 23,
//     Aug: 51.4,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 15,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 16,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 17,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 18,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 2,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 19,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 7,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 20,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 5,
//     Aug: 3,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 21,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 74.2,
//     Aug: 0,
//     Sept: 1.6,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 22,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 23,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 62,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 24,
//     Jan: 1,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 13.3,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 25,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 0,
//     Aug: 22.8,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 26,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 1.2,
//     July: 17.4,
//     Aug: 35.2,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 27,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 38.2,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 28,
//     Jan: 0,
//     Feb: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 10.2,
//     July: 0,
//     Aug: 0,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 29,
//     Jan: 0,
//     March: 0,
//     April: 0,
//     May: 0,
//     June: 0,
//     July: 74,
//     Aug: 1,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 30,
//     Jan: 0,
//     March: 0,
//     April: 8.8,
//     May: 0,
//     June: 1,
//     July: 9.6,
//     Aug: 26,
//     Sept: 0,
//     Oct: 0,
//     Nov: 0,
//     Dec: 0,
//   },
//   {
//     Day: 31,
//     Jan: 0,
//     March: 0,
//     May: 0,
//     July: 6.6,
//     Aug: 2.8,
//     Oct: 0,
//     Dec: 0,
//   },
// ];

export const YearWiseRainfallData = [
  { x: 2017, y: 883.0 },
  { x: 2018, y: 836.6 },
  { x: 2019, y: 1033.2 },
  { x: 2020, y: 1089.4 },
  { x: 2021, y: 1053.0 },
];
